### ISSUE TITLE
Script Design - Action Edits - Changes not stored

### ISSUE THREAD

**Issue by NairiBonte** [metadew/iesi-ui#106]
Screen: Script Design (detail)
Functionality: Perform edit on existing action (action parameters - description)

Description: Performed changes/edits on an existing action are not stored when saving the modifications. Original input remains.

Steps to reproduce:

1. Open script design & modify existing action (e.g. change the action description)
2. Save the modification in current script version (Save > Update current version)
3. Leave the script design screen (e.g. go back to script overview)
4. Lookup the modified script/actions

Actual:
= original description still visible - edit(s) were not stored

Expected:
= modified/updated description is visible - edit(s) were correctly stored

**Comment by Suyash-d** [comment]
This is not issue with UI, its because of core
